version: '3'
services:
#  bind:
  nginx:
    image: nginx
    volumes: 
      - conf:/etc/
    ports:
      - "80:80"
  
#  mysql:
#  ldap:
volumes:
  conf:
    driver_opts:
      type: none
      device: /conf
      o: bind
  data:
    driver_opts:
      type: none
      device: /data  
      o: bind
